name: flutter_pdfview
description: A Flutter plugin that provides a PDFView widget on Android and iOS.
version: 1.3.1
homepage: https://github.com/endigo/flutter_pdfview

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  app_settings: ^4.2.0
  flutter:
    sdk: flutter
  permission_handler: ^10.3.0
  path_provider: ^2.0.11
  file_manager: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.endigo.plugins.pdfviewflutter
        pluginClass: PDFViewFlutterPlugin
      ios:
        pluginClass: FLTPDFViewFlutterPlugin
